### ISSUE TITLE
running oim transfer throws "Error: Cannot find module '../build/Debug/nodegit.node'"

### ISSUE THREAD

**Issue by fluxthedev** [leedium/occ-instance-migrator#10]
Here is full error, followed parameters from read me: 

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/johnore/Downloads/occ-instance-migrator-master/node_modules/nodegit-kit/node_modules/nodegit/dist/nodegit.js:19:12)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by leedium** [comment]
Cool thanks.  Are you on windows or osx?  I'm going to try and recreate.

Sorry for the error... (works on my machine)

D.

**Comment by leedium** [comment]
I just tested and nodegit is successfully creating the temp repo for me.
What version of node are you running?  I'm v8.11.1.
Make sure your working folder is not the folder you are cloning the tool to.

Check this out:
Could be an issue with nodegit.
https://github.com/nodegit/nodegit/issues/137

If that is not still working, branch v2.0.0 is the version that should work with your os installed version of git.  Maybe give that a shot.

**Comment by ptolbert** [comment]
I also ran into this nodegit error -- after an hour or so of Googling I found thousands of folks with a similar issue. Most of us are noobs, and manually installing nodegit globally seems to have solved the issue for me.

**Comment by leedium** [comment]
> I also ran into this nodegit error -- after an hour or so of Googling I found thousands of folks with a similar issue. Most of us are noobs, and manually installing nodegit globally seems to have solved the issue for me.

Nice one man, I'll try a global install and see if it works. (...when it does work, it's pretty cool beans)
:)

**Comment by ptolbert** [comment]
Additionally, Node 10 seems to have widespread issues, I'm going to try a complete install with version~8ish.

**Comment by leedium** [comment]
> Additionally, Node 10 seems to have widespread issues, I'm going to try a complete install with version~8ish.

Yea, I did a test a few weeks ago and v8.11.1 worked like a charm (not global) . Make sure you uninstall everything and blow away ur node_modules folder.

**Comment by ptolbert** [comment]
I have a bout a million node_modules folders from failed attempts to fix DCU, etc. Here goes nothing.

**Comment by leedium** [comment]
FYI, there are some MAJOR issues with DCU itself so, use this tool sparingly.  lol. ... This tools is only as good as the DCU is working.  Oracle is working on it.  The team they have there is really good.  Nice people too.
